[package]
name = "airplay-lib"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
ed25519-dalek = { version = "2", features = ["rand_core"] }
x25519-dalek = { version = "2", features = ["static_secrets", "reusable_secrets"] }
aes = "0.8"
ctr = "0.9"
sha2 = "0.10"
rand_core = { version = "0.6", features = ["getrandom"] }
