[package]
name = "airplay-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "airplay-app"
path = "src/main.rs"

[features]
default = ["h264-dump"]
h264-dump = ["airplay-player/h264-dump"]
gstreamer = ["airplay-player/gstreamer"]
ffmpeg = ["airplay-player/ffmpeg"]
vlc = ["airplay-player/vlc"]

[dependencies]
airplay-server = { workspace = true }
airplay-player = { workspace = true, default-features = false }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
